<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentSeeder extends Seeder
{
    public function run()
    {
        $departments = [
            // Level 0 - Trường Đại học
            [
                'id' => 1,
                'name' => 'Trường Đại học Thủy lợi',
                'code' => 'TLU',
                'parent_id' => null,
                'user_id' => 1,
                'description' => 'Trường Đại học Thủy lợi là một trong những trường đại học kỹ thuật hàng đầu Việt Nam trong lĩnh vực thủy lợi, xây dựng và môi trường.',
                'phone' => '024.38522201',
                'email' => 'tlu@tlu.edu.vn',
                'address' => '175 Tây Sơn, Đống Đa, Hà Nội',
                'level' => 0,
                'department_type' => 'administrative' // Đơn vị hành chính
            ],

            // Level 1 - Các Khoa (Đơn vị đào tạo)
            [
                'id' => 2,
                'name' => 'Khoa Công trình',
                'code' => 'CT',
                'parent_id' => 1,
                'user_id' => 2,
                'description' => 'Khoa Công trình chuyên đào tạo các ngành kỹ thuật xây dựng công trình thủy, dân dụng và giao thông.',
                'phone' => '024.38522210',
                'email' => 'congtrinh@tlu.edu.vn',
                'address' => 'Tòa nhà A2, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic' // Đơn vị đào tạo
            ],
            [
                'id' => 3,
                'name' => 'Khoa Kỹ thuật tài nguyên nước',
                'code' => 'KTTNR',
                'parent_id' => 1,
                'user_id' => 3,
                'description' => 'Khoa chuyên về kỹ thuật tài nguyên nước, cấp thoát nước và thủy văn học.',
                'phone' => '024.38522215',
                'email' => 'tainguyennuoc@tlu.edu.vn',
                'address' => 'Tòa nhà A3, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 4,
                'name' => 'Khoa Cơ khí',
                'code' => 'CK',
                'parent_id' => 1,
                'user_id' => 4,
                'description' => 'Khoa Cơ khí đào tạo các ngành kỹ thuật cơ khí, chế tạo máy, ô tô và cơ điện tử.',
                'phone' => '024.38522220',
                'email' => 'cokhi@tlu.edu.vn',
                'address' => 'Tòa nhà B1, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 5,
                'name' => 'Khoa Điện – Điện tử',
                'code' => 'DDT',
                'parent_id' => 1,
                'user_id' => 5,
                'description' => 'Khoa đào tạo các ngành kỹ thuật điện, điện tử viễn thông, tự động hóa và robot.',
                'phone' => '024.38522225',
                'email' => 'diendt@tlu.edu.vn',
                'address' => 'Tòa nhà B2, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 6,
                'name' => 'Khoa Kinh tế và quản lý',
                'code' => 'KTQL',
                'parent_id' => 1,
                'user_id' => 6,
                'description' => 'Khoa đào tạo các ngành kinh tế, quản trị kinh doanh, thương mại điện tử và du lịch.',
                'phone' => '024.38522230',
                'email' => 'ktql@tlu.edu.vn',
                'address' => 'Tòa nhà A5, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 7,
                'name' => 'Khoa Công nghệ thông tin',
                'code' => 'CNTT',
                'parent_id' => 1,
                'user_id' => 7,
                'description' => 'Khoa đào tạo các ngành công nghệ thông tin, an ninh mạng và trí tuệ nhân tạo.',
                'phone' => '024.38522235',
                'email' => 'cntt@tlu.edu.vn',
                'address' => 'Tòa nhà C5, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 8,
                'name' => 'Khoa Hóa và Môi trường',
                'code' => 'HMT',
                'parent_id' => 1,
                'user_id' => 8,
                'description' => 'Khoa đào tạo các ngành kỹ thuật môi trường, hóa học và công nghệ sinh học.',
                'phone' => '024.38522240',
                'email' => 'hoamt@tlu.edu.vn',
                'address' => 'Tòa nhà D1, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 9,
                'name' => 'Khoa Luật và Lý luận chính trị',
                'code' => 'LLLCT',
                'parent_id' => 1,
                'user_id' => 9,
                'description' => 'Khoa đào tạo ngành Luật và Luật kinh tế.',
                'phone' => '024.38522245',
                'email' => 'luat@tlu.edu.vn',
                'address' => 'Tòa nhà A1, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 10,
                'name' => 'Trung tâm Đào tạo quốc tế',
                'code' => 'TTDTQT',
                'parent_id' => 1,
                'user_id' => 10,
                'description' => 'Trung tâm đào tạo các chương trình quốc tế và ngoại ngữ.',
                'phone' => '024.38522250',
                'email' => 'international@tlu.edu.vn',
                'address' => 'Tòa nhà A6, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],
            [
                'id' => 11,
                'name' => 'Khoa Kế toán và Kinh doanh',
                'code' => 'KTKD',
                'parent_id' => 1,
                'user_id' => 11,
                'description' => 'Khoa đào tạo các ngành kế toán, kiểm toán, tài chính ngân hàng.',
                'phone' => '024.38522255',
                'email' => 'ketoan@tlu.edu.vn',
                'address' => 'Tòa nhà A7, Trường Đại học Thủy lợi',
                'level' => 1,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Công trình
            [
                'id' => 41,
                'name' => 'Bộ môn Kỹ thuật xây dựng công trình thủy',
                'code' => 'KTXDCTT',
                'parent_id' => 2,
                'user_id' => 41,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật xây dựng công trình thủy.',
                'phone' => '024.38522211',
                'email' => 'ktxdctt@tlu.edu.vn',
                'address' => 'Tòa nhà A2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 42,
                'name' => 'Bộ môn Xây dựng dân dụng và công nghiệp',
                'code' => 'XDDVCN',
                'parent_id' => 2,
                'user_id' => 42,
                'description' => 'Bộ môn chuyên đào tạo ngành Xây dựng dân dụng và công nghiệp.',
                'phone' => '024.38522212',
                'email' => 'xddvcn@tlu.edu.vn',
                'address' => 'Tòa nhà A2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 43,
                'name' => 'Bộ môn Xây dựng cầu đường',
                'code' => 'XDCD',
                'parent_id' => 2,
                'user_id' => 43,
                'description' => 'Bộ môn chuyên đào tạo ngành Xây dựng cầu đường.',
                'phone' => '024.38522213',
                'email' => 'xdcd@tlu.edu.vn',
                'address' => 'Tòa nhà A2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 44,
                'name' => 'Bộ môn Vật liệu xây dựng',
                'code' => 'VLXD',
                'parent_id' => 2,
                'user_id' => 44,
                'description' => 'Bộ môn chuyên về vật liệu xây dựng và công nghệ mới.',
                'phone' => '024.38522214',
                'email' => 'vlxd@tlu.edu.vn',
                'address' => 'Tòa nhà A2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Kỹ thuật tài nguyên nước
            [
                'id' => 45,
                'name' => 'Bộ môn Thủy văn',
                'code' => 'TV',
                'parent_id' => 3,
                'user_id' => 45,
                'description' => 'Bộ môn chuyên đào tạo ngành Thủy văn học.',
                'phone' => '024.38522216',
                'email' => 'thuyvan@tlu.edu.vn',
                'address' => 'Tòa nhà A3, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 46,
                'name' => 'Bộ môn Cấp thoát nước',
                'code' => 'CTN',
                'parent_id' => 3,
                'user_id' => 46,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật cấp thoát nước.',
                'phone' => '024.38522217',
                'email' => 'capthoatnuoc@tlu.edu.vn',
                'address' => 'Tòa nhà A3, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 47,
                'name' => 'Bộ môn Kỹ thuật tài nguyên nước',
                'code' => 'KTTN',
                'parent_id' => 3,
                'user_id' => 47,
                'description' => 'Bộ môn chuyên về quản lý và khai thác tài nguyên nước.',
                'phone' => '024.38522218',
                'email' => 'kttn@tlu.edu.vn',
                'address' => 'Tòa nhà A3, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Cơ khí
            [
                'id' => 48,
                'name' => 'Bộ môn Kỹ thuật cơ khí',
                'code' => 'KTCK',
                'parent_id' => 4,
                'user_id' => 48,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật cơ khí.',
                'phone' => '024.38522221',
                'email' => 'ktck@tlu.edu.vn',
                'address' => 'Tòa nhà B1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 49,
                'name' => 'Bộ môn Công nghệ chế tạo máy',
                'code' => 'CNCTM',
                'parent_id' => 4,
                'user_id' => 49,
                'description' => 'Bộ môn chuyên đào tạo ngành Công nghệ chế tạo máy.',
                'phone' => '024.38522222',
                'email' => 'cnctm@tlu.edu.vn',
                'address' => 'Tòa nhà B1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 50,
                'name' => 'Bộ môn Kỹ thuật ô tô',
                'code' => 'KTOT',
                'parent_id' => 4,
                'user_id' => 50,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật ô tô.',
                'phone' => '024.38522223',
                'email' => 'ktot@tlu.edu.vn',
                'address' => 'Tòa nhà B1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 51,
                'name' => 'Bộ môn Cơ điện tử',
                'code' => 'CDT',
                'parent_id' => 4,
                'user_id' => 51,
                'description' => 'Bộ môn chuyên đào tạo ngành Cơ điện tử.',
                'phone' => '024.38522224',
                'email' => 'codientu@tlu.edu.vn',
                'address' => 'Tòa nhà B1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Điện - Điện tử
            [
                'id' => 52,
                'name' => 'Bộ môn Kỹ thuật điện',
                'code' => 'KTD',
                'parent_id' => 5,
                'user_id' => 52,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật điện.',
                'phone' => '024.38522226',
                'email' => 'ktdien@tlu.edu.vn',
                'address' => 'Tòa nhà B2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 53,
                'name' => 'Bộ môn Điện tử viễn thông',
                'code' => 'DTVT',
                'parent_id' => 5,
                'user_id' => 53,
                'description' => 'Bộ môn chuyên đào tạo ngành Điện tử viễn thông.',
                'phone' => '024.38522227',
                'email' => 'dtvt@tlu.edu.vn',
                'address' => 'Tòa nhà B2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 54,
                'name' => 'Bộ môn Kỹ thuật điều khiển và Tự động hóa',
                'code' => 'KTDKTDH',
                'parent_id' => 5,
                'user_id' => 54,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật điều khiển và tự động hóa.',
                'phone' => '024.38522228',
                'email' => 'tudonghua@tlu.edu.vn',
                'address' => 'Tòa nhà B2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 55,
                'name' => 'Bộ môn Robot và Trí tuệ nhân tạo',
                'code' => 'RTTNT',
                'parent_id' => 5,
                'user_id' => 55,
                'description' => 'Bộ môn chuyên đào tạo ngành Robot và trí tuệ nhân tạo.',
                'phone' => '024.38522229',
                'email' => 'robotai@tlu.edu.vn',
                'address' => 'Tòa nhà B2, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Công nghệ thông tin
            [
                'id' => 56,
                'name' => 'Bộ môn Công nghệ phần mềm',
                'code' => 'CNPM',
                'parent_id' => 7,
                'user_id' => 56,
                'description' => 'Bộ môn chuyên đào tạo ngành Công nghệ phần mềm.',
                'phone' => '024.38522236',
                'email' => 'cnpm@tlu.edu.vn',
                'address' => 'Tòa nhà C5, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 57,
                'name' => 'Bộ môn Hệ thống thông tin',
                'code' => 'HTTT',
                'parent_id' => 7,
                'user_id' => 57,
                'description' => 'Bộ môn chuyên đào tạo ngành Hệ thống thông tin.',
                'phone' => '024.38522237',
                'email' => 'httt@tlu.edu.vn',
                'address' => 'Tòa nhà C5, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 58,
                'name' => 'Bộ môn An toàn thông tin',
                'code' => 'ATTT',
                'parent_id' => 7,
                'user_id' => 58,
                'description' => 'Bộ môn chuyên đào tạo ngành An toàn thông tin.',
                'phone' => '024.38522238',
                'email' => 'attt@tlu.edu.vn',
                'address' => 'Tòa nhà C5, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 59,
                'name' => 'Bộ môn Khoa học máy tính',
                'code' => 'KHMT',
                'parent_id' => 7,
                'user_id' => 59,
                'description' => 'Bộ môn chuyên đào tạo ngành Khoa học máy tính.',
                'phone' => '024.38522239',
                'email' => 'khmt@tlu.edu.vn',
                'address' => 'Tòa nhà C5, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Luật và Lý luận chính trị
            [
                'id' => 60,
                'name' => 'Bộ môn Luật',
                'code' => 'L',
                'parent_id' => 9,
                'user_id' => 60,
                'description' => 'Bộ môn chuyên đào tạo ngành Luật.',
                'phone' => '024.38522246',
                'email' => 'luat_bm@tlu.edu.vn',
                'address' => 'Tòa nhà A1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 61,
                'name' => 'Bộ môn Luật kinh tế',
                'code' => 'LKT',
                'parent_id' => 9,
                'user_id' => 61,
                'description' => 'Bộ môn chuyên đào tạo ngành Luật kinh tế.',
                'phone' => '024.38522247',
                'email' => 'luatkinhte@tlu.edu.vn',
                'address' => 'Tòa nhà A1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 62,
                'name' => 'Bộ môn Lý luận chính trị',
                'code' => 'LLCT',
                'parent_id' => 9,
                'user_id' => 62,
                'description' => 'Bộ môn giảng dạy các môn lý luận chính trị.',
                'phone' => '024.38522248',
                'email' => 'llct@tlu.edu.vn',
                'address' => 'Tòa nhà A1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Kinh tế và quản lý (đã có từ trước)
            [
                'id' => 12,
                'name' => 'Bộ môn Thương mại điện tử',
                'code' => 'TMDT',
                'parent_id' => 6,
                'user_id' => 12,
                'description' => 'Bộ môn chuyên đào tạo ngành Thương mại điện tử.',
                'phone' => '024.38522231',
                'email' => 'tmdt@tlu.edu.vn',
                'address' => 'P208 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 13,
                'name' => 'Bộ môn Quản trị du lịch',
                'code' => 'QTDL',
                'parent_id' => 6,
                'user_id' => 13,
                'description' => 'Bộ môn chuyên đào tạo ngành Quản trị dịch vụ du lịch và lữ hành.',
                'phone' => '024.38522232',
                'email' => 'dulich@tlu.edu.vn',
                'address' => 'P209 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 14,
                'name' => 'Bộ môn Kinh tế',
                'code' => 'KT',
                'parent_id' => 6,
                'user_id' => 14,
                'description' => 'Bộ môn chuyên đào tạo ngành Kinh tế.',
                'phone' => '024.38522233',
                'email' => 'kinhte@tlu.edu.vn',
                'address' => 'P210 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 15,
                'name' => 'Bộ môn Kinh tế xây dựng',
                'code' => 'KTXD',
                'parent_id' => 6,
                'user_id' => 15,
                'description' => 'Bộ môn chuyên đào tạo ngành Kinh tế xây dựng.',
                'phone' => '024.38522234',
                'email' => 'ktxd@tlu.edu.vn',
                'address' => 'P211 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 16,
                'name' => 'Bộ môn Phát triển kỹ năng',
                'code' => 'PTKN',
                'parent_id' => 6,
                'user_id' => 16,
                'description' => 'Bộ môn chuyên về phát triển kỹ năng mềm cho sinh viên.',
                'phone' => '024.38522235',
                'email' => 'ptkn@tlu.edu.vn',
                'address' => 'P214 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 17,
                'name' => 'Bộ môn Kinh tế và kinh doanh số',
                'code' => 'KTKDS',
                'parent_id' => 6,
                'user_id' => 17,
                'description' => 'Bộ môn chuyên đào tạo ngành Kinh tế số.',
                'phone' => '024.38522236',
                'email' => 'kinhteaso@tlu.edu.vn',
                'address' => 'P202 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 18,
                'name' => 'Bộ môn Logistics và chuỗi cung ứng',
                'code' => 'LCCCU',
                'parent_id' => 6,
                'user_id' => 18,
                'description' => 'Bộ môn chuyên đào tạo ngành Logistics và quản lý chuỗi cung ứng.',
                'phone' => '024.38522237',
                'email' => 'logistics@tlu.edu.vn',
                'address' => 'P203-204-205 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 19,
                'name' => 'Trung tâm Kinh tế và Quản lý',
                'code' => 'TTKTQL',
                'parent_id' => 6,
                'user_id' => 19,
                'description' => 'Trung tâm nghiên cứu và ứng dụng trong lĩnh vực kinh tế và quản lý.',
                'phone' => '024.38522238',
                'email' => 'ttktql@tlu.edu.vn',
                'address' => 'P212-213 nhà A5',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Hóa và Môi trường
            [
                'id' => 20,
                'name' => 'Bộ môn Kỹ thuật và Quản lý Môi trường',
                'code' => 'KTQLMT',
                'parent_id' => 8,
                'user_id' => 20,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật môi trường.',
                'phone' => '024.38522241',
                'email' => 'moitruong@tlu.edu.vn',
                'address' => 'Tòa nhà D1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 21,
                'name' => 'Bộ môn Kỹ thuật Hóa học',
                'code' => 'KTHH',
                'parent_id' => 8,
                'user_id' => 21,
                'description' => 'Bộ môn chuyên đào tạo ngành Kỹ thuật hóa học.',
                'phone' => '024.38522242',
                'email' => 'hoahoc@tlu.edu.vn',
                'address' => 'Tòa nhà D1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 22,
                'name' => 'Bộ môn Công nghệ Sinh học',
                'code' => 'CNSH',
                'parent_id' => 8,
                'user_id' => 22,
                'description' => 'Bộ môn chuyên đào tạo ngành Công nghệ sinh học.',
                'phone' => '024.38522243',
                'email' => 'sinhhoc@tlu.edu.vn',
                'address' => 'Tòa nhà D1, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Trung tâm Đào tạo quốc tế
            [
                'id' => 23,
                'name' => 'Bộ môn ngôn ngữ Anh',
                'code' => 'NNA',
                'parent_id' => 10,
                'user_id' => 23,
                'description' => 'Bộ môn chuyên đào tạo ngành Ngôn ngữ Anh.',
                'phone' => '024.38522251',
                'email' => 'english@tlu.edu.vn',
                'address' => 'Tòa nhà A6, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 24,
                'name' => 'Bộ môn ngôn ngữ Trung Quốc',
                'code' => 'NNTQ',
                'parent_id' => 10,
                'user_id' => 24,
                'description' => 'Bộ môn chuyên đào tạo ngành Ngôn ngữ Trung Quốc.',
                'phone' => '024.38522252',
                'email' => 'chinese@tlu.edu.vn',
                'address' => 'Tòa nhà A6, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 2 - Bộ môn thuộc Khoa Kế toán và Kinh doanh
            [
                'id' => 25,
                'name' => 'Bộ môn kế toán',
                'code' => 'KT_BM',
                'parent_id' => 11,
                'user_id' => 25,
                'description' => 'Bộ môn chuyên đào tạo ngành Kế toán.',
                'phone' => '024.38522256',
                'email' => 'ketoan_bm@tlu.edu.vn',
                'address' => 'Tòa nhà A7, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 26,
                'name' => 'Bộ môn kiểm toán',
                'code' => 'KTA',
                'parent_id' => 11,
                'user_id' => 26,
                'description' => 'Bộ môn chuyên đào tạo ngành Kiểm toán.',
                'phone' => '024.38522257',
                'email' => 'kiemtoan@tlu.edu.vn',
                'address' => 'Tòa nhà A7, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 27,
                'name' => 'Bộ môn tài chính',
                'code' => 'TC',
                'parent_id' => 11,
                'user_id' => 27,
                'description' => 'Bộ môn chuyên đào tạo ngành Tài chính - Ngân hàng.',
                'phone' => '024.38522258',
                'email' => 'taichinh@tlu.edu.vn',
                'address' => 'Tòa nhà A7, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],
            [
                'id' => 28,
                'name' => 'Bộ Môn Quản trị kinh doanh',
                'code' => 'QTKD',
                'parent_id' => 11,
                'user_id' => 28,
                'description' => 'Bộ môn chuyên đào tạo ngành Quản trị kinh doanh.',
                'phone' => '024.38522259',
                'email' => 'qtkd@tlu.edu.vn',
                'address' => 'Tòa nhà A7, Trường Đại học Thủy lợi',
                'level' => 2,
                'department_type' => 'academic'
            ],

            // Level 1 - Các Phòng ban hành chính (Đơn vị hành chính)
            [
                'id' => 29,
                'name' => 'Phòng Hành chính - Tổng hợp',
                'code' => 'HCTH',
                'parent_id' => 1,
                'user_id' => 29,
                'description' => 'Công tác văn thư lưu trữ; Kế hoạch - tổng hợp; Công tác cải cách hành chính; Phục vụ, lễ tân; Đối ngoại; Thanh tra; Pháp chế.',
                'phone' => '024.38522201',
                'email' => 'phonghcth@tlu.edu.vn',
                'address' => 'P.200, P.203, P.204, P.111, P.113 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 30,
                'name' => 'Phòng Tổ chức cán bộ',
                'code' => 'TCCB',
                'parent_id' => 1,
                'user_id' => 30,
                'description' => 'Công tác tổ chức bộ máy và thể chế hoạt động; Quản lý biên chế, nhân sự; Chế độ chính sách; Đào tạo, bồi dưỡng; Thi đua khen thưởng.',
                'phone' => '024.35633086',
                'email' => 'p2@tlu.edu.vn',
                'address' => 'P.209, P.211, P.213 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 31,
                'name' => 'Phòng Đào tạo',
                'code' => 'DT',
                'parent_id' => 1,
                'user_id' => 31,
                'description' => 'Công tác tuyển sinh; Xây dựng và quản lý chương trình đào tạo; Tổ chức và quản lý đào tạo các bậc, loại hình; Phát triển đào tạo.',
                'phone' => '024.38521441',
                'email' => 'daotao@tlu.edu.vn',
                'address' => 'P.130, P.132, P.134 nhà A4',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 32,
                'name' => 'Phòng Khảo thí và Đảm bảo chất lượng',
                'code' => 'KTDBCL',
                'parent_id' => 1,
                'user_id' => 32,
                'description' => 'Tổ chức và quản lý công tác khảo thí; Quản lý công tác đánh giá và đảm bảo chất lượng giáo dục.',
                'phone' => '024.35643417',
                'email' => 'phongktkdcl@tlu.edu.vn',
                'address' => 'P.115, P.104 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 33,
                'name' => 'Phòng Chính trị và Công tác sinh viên',
                'code' => 'CTCTSV',
                'parent_id' => 1,
                'user_id' => 33,
                'description' => 'Công tác chính trị tư tưởng cho cán bộ viên chức và sinh viên; Công tác thông tin, tuyên truyền; Công tác sinh viên.',
                'phone' => '024.35639577',
                'email' => 'p7@tlu.edu.vn',
                'address' => 'P.110, P.112, P.116, P.118 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 34,
                'name' => 'Phòng Khoa học công nghệ và Hợp tác quốc tế',
                'code' => 'KHCNHTQT',
                'parent_id' => 1,
                'user_id' => 34,
                'description' => 'Tổ chức và quản lý nghiên cứu khoa học, chuyển giao công nghệ; Quản lý hoạt động hợp tác quốc tế; Xây dựng và triển khai dự án quốc tế.',
                'phone' => '024.38533083',
                'email' => 'kncn@tlu.edu.vn',
                'address' => 'P.103, P.105, P.508, P.510 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 35,
                'name' => 'Phòng Tài chính - Kế toán',
                'code' => 'TCKT',
                'parent_id' => 1,
                'user_id' => 35,
                'description' => 'Xây dựng và quản lý kế hoạch về tài chính; Tổ chức, quản lý, khai thác và sử dụng hiệu quả các nguồn tài chính; Tổ chức công tác kế toán.',
                'phone' => '024.35634602',
                'email' => 'phongtaivu@tlu.edu.vn',
                'address' => 'P.215, P.217, P.219, P.221 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 36,
                'name' => 'Phòng Quản trị - Thiết bị',
                'code' => 'QTTB',
                'parent_id' => 1,
                'user_id' => 36,
                'description' => 'Quản lý và khai thác hệ thống cơ sở vật chất, hạ tầng, trang thiết bị; Quản lý đầu tư xây dựng; Phòng cháy, chữa cháy; An ninh trật tự.',
                'phone' => '024.35635671',
                'email' => 'quantri@tlu.edu.vn',
                'address' => 'P.101, P.102, P.103, P.104 nhà A5; P.109 nhà A1',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 37,
                'name' => 'Trung tâm Nội trú',
                'code' => 'TTNT',
                'parent_id' => 1,
                'user_id' => 37,
                'description' => 'Quản lý và đảm bảo các điều kiện sinh hoạt trong khu nội trú; Đảm bảo an ninh trật tự; Quản lý dịch vụ ăn, uống và căng tin.',
                'phone' => '024.35643058',
                'email' => 'banquanly_ktx@tlu.edu.vn',
                'address' => 'P.303, P.305 KTX K1; Nhà 2, Nhà 3, Nhà 4',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 38,
                'name' => 'Trung tâm Tin học',
                'code' => 'TTTH',
                'parent_id' => 1,
                'user_id' => 38,
                'description' => 'Công tác tin học hóa quản trị điều hành và quản lý hành chính; Nghiên cứu, ứng dụng, đào tạo và dịch vụ công nghệ thông tin.',
                'phone' => '024.35635915',
                'email' => 'ttth@tlu.edu.vn',
                'address' => 'Phòng trực nhà C5; P.204 nhà C5; P.104 Tòa nhà A45',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 39,
                'name' => 'Thư viện',
                'code' => 'TV',
                'parent_id' => 1,
                'user_id' => 39,
                'description' => 'Lưu trữ, khai thác, thu thập, bảo quản, quản lý sách báo, tạp chí, giáo trình, tài liệu điện tử; Cung cấp thông tin phục vụ giảng dạy và nghiên cứu.',
                'phone' => '024.35640068',
                'email' => 'thuvien@tlu.edu.vn',
                'address' => 'P.207, P.205, P.305 Tòa nhà A45',
                'level' => 1,
                'department_type' => 'administrative'
            ],
            [
                'id' => 40,
                'name' => 'Trạm Y tế',
                'code' => 'TYT',
                'parent_id' => 1,
                'user_id' => 40,
                'description' => 'Công tác quản lý và chăm sóc sức khỏe ban đầu cho cán bộ viên chức và sinh viên; Y tế học đường, phòng chống dịch bệnh và giữ gìn vệ sinh.',
                'phone' => '024.35632839',
                'email' => 'tramyte@tlu.edu.vn',
                'address' => 'KTX Nhà 4',
                'level' => 1,
                'department_type' => 'administrative'
            ],
        ];

        foreach ($departments as $department) {
            DB::table('departments')->insert([
                'id' => $department['id'],
                'name' => $department['name'],
                'code' => $department['code'],
                'parent_id' => $department['parent_id'],
                'user_id' => $department['user_id'],
                'description' => $department['description'],
                'phone' => $department['phone'],
                'email' => $department['email'],
                'address' => $department['address'],
                'level' => $department['level'],
                'department_type' => $department['department_type'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}